name: North By Midwest
description: |
  A story about a Jackass
characters:
  render: true
  description: |
    The characters
  list:
    -
      id: jackass
      name: Jackass
      role: lead
      images:
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/2/1466/25906665132_fd019fc525_z.jpg
          display: https://c2.staticflickr.com/2/1466/25906665132_fd019fc525_b.jpg
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5755/22569031093_aeb7dbdbe3.jpg
          display: https://c2.staticflickr.com/6/5755/22569031093_aeb7dbdbe3_b.jpg
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5738/23196101915_c185d909b3.jpg
          display: https://c2.staticflickr.com/6/5738/23196101915_c185d909b3_b.jpg
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5631/22828141069_76e4885915.jpg
          display: https://c2.staticflickr.com/6/5631/22828141069_76e4885915_b.jpg
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/1/763/22569031513_86013833e4.jpg
          display: https://c1.staticflickr.com/1/763/22569031513_86013833e4_b.jpg
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/1/626/22569031703_935c0752f9.jpg
          display: https://c1.staticflickr.com/1/626/22569031703_935c0752f9_b.jpg
      description: |
        Jackass is the lead character. He's not dopey, but he is naïve somewhat.
    -
      id: fanny
      name: Fanny
      role: lead
      images:
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/1/757/22567619524_b18acc8320.jpg
          display: https://c1.staticflickr.com/1/757/22567619524_b18acc8320_b.jpg
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/1/675/22900306400_6c1e9e7b72.jpg
          display: https://c1.staticflickr.com/1/675/22900306400_6c1e9e7b72_b.jpg
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/1/604/23196102435_5936421e7f.jpg
          display: https://c1.staticflickr.com/1/604/23196102435_5936421e7f_b.jpg
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5755/23170008876_c40bd5638f.jpg
          display: https://c2.staticflickr.com/6/5755/23170008876_c40bd5638f_b.jpg
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5655/23196102585_1b82cb21c3.jpg
          display: https://c2.staticflickr.com/6/5655/23196102585_1b82cb21c3_b.jpg
      description: |
        She a gold digger
    -
      id: neil
      name: Neil Wolfhound
      role: lead
      images:
        -
          orientation: landscape
          thumbnail: https://c2.staticflickr.com/2/1569/25314140621_a574c8a913_z.jpg
          display: https://c2.staticflickr.com/2/1569/25314140621_6fe0e02d5f_h.jpg
        -
          orientation: landscape
          thumbnail: https://c2.staticflickr.com/2/1712/24780425733_d5c99f2ce8_z.jpg
          display: https://c2.staticflickr.com/2/1712/24780425733_3bff67e5ba_h.jpg
      description: |
        He is a hound dog.
    -
      id: rabbi
      name: Rabbi
      role: lead
      images:
        -
          orientation: landscape
          thumbnail: https://c2.staticflickr.com/2/1560/25380972016_6b37ef4f7e_z.jpg
          display: https://c2.staticflickr.com/2/1560/25380972016_983f3f869d_h.jpg
      description: |
        she's a Cow Rabbi
    -
      id: chickenbutt
      name: Chicken Butt
      role: supporting
      images:
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/2/1593/24602904065_5972a741e3_z.jpg
          display: https://c2.staticflickr.com/2/1593/24602904065_1a5d24fabd_h.jpg
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/2/1504/24602586495_d56cd77d1d_z.jpg
          display: https://c2.staticflickr.com/2/1504/24602586495_aca90c3e1c_h.jpg
      description: |
        Random supporting character
resources: >

  * [Original PDF of the book from Jon](https://drive.google.com/open?id=0B3I1UYm_FEJrajF2d1pSMTM2MzQ)

  * myscriptfont.com for the text

  <a data-pin-do="embedBoard" href="https://www.pinterest.com/dethbird/illustration-early-1900s/" data-pin-scale-width="266" data-pin-scale-height="266" data-pin-board-width="800" data-pin-board-height="800">        Follow dethbird's board illustration early 1900s on Pinterest.</a>
storyboards:
  -
    name: Book 01
    boards:
      -
        id: nxmw-storyboard-00
        notes: |
          blank
        images:
          -
            orientation: portrait
            thumbnail: http://vignette2.wikia.nocookie.net/uncyclopedia/images/4/44/White_square.png/revision/20061003200039
            display: http://vignette2.wikia.nocookie.net/uncyclopedia/images/4/44/White_square.png/revision/20061003200039
      -
        id: nxmw-storyboard-01
        notes: |
          cover
        images:
          -
            orientation: portrait
            thumbnail: https://c2.staticflickr.com/2/1473/25309649683_87c479fa2a_b.jpg
            display: https://c2.staticflickr.com/2/1473/25309649683_87c479fa2a_b.jpg
          -
            orientation: portrait
            thumbnail: https://c2.staticflickr.com/2/1716/25881124155_0de98c57eb_c.jpg
            display: https://c2.staticflickr.com/2/1716/25881124155_69a435b845_o.jpg
      -
        id: nxmw-storyboard-02
        notes: |
          inside cover
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1452/26254803722_737d9d7407_z.jpg
            display: https://c2.staticflickr.com/2/1452/26254803722_737d9d7407_b.jpg
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1444/25305663964_023b9c3289_c.jpg
            display: https://c2.staticflickr.com/2/1444/25305663964_023b9c3289_b.jpg
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1505/25913090905_f00816b98c_c.jpg
            display: https://c2.staticflickr.com/2/1505/25913090905_f00816b98c_b.jpg
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1473/25580660310_ef72f451a5_c.jpg
            display: https://c2.staticflickr.com/2/1473/25580660310_fbeb8bd33f_o.jpg
      -
        id: nxmw-storyboard-03
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1605/25843409051_9f429bfee4_c.jpg
            display: https://c2.staticflickr.com/2/1605/25843409051_9f429bfee4_b.jpg
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1700/25283634003_5d9faa88d2_b.jpg
            display: https://c2.staticflickr.com/2/1700/25283634003_5d9faa88d2_b.jpg
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1541/25881251765_b47d3925e9_c.jpg
            display: https://c2.staticflickr.com/2/1541/25881251765_0514ca1df2_o.jpg
      -
        id: nxmw-storyboard-04
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1529/25844387611_787733d323_c.jpg
            display: https://c2.staticflickr.com/2/1529/25844387611_787733d323_b.jpg
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1550/25782195352_472e38e076_c.jpg
            display: https://c2.staticflickr.com/2/1550/25782195352_472e38e076_b.jpg
      -
        id: nxmw-storyboard-05
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1688/25820414692_2297a9133e_c.jpg
            display: https://c2.staticflickr.com/2/1688/25820414692_2297a9133e_b.jpg
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1520/25309640893_8e8b8ba646_c.jpg
            display: https://c2.staticflickr.com/2/1520/25309640893_8e8b8ba646_b.jpg
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1533/25817003901_4cd3272601_c.jpg
            display: https://c2.staticflickr.com/2/1533/25817003901_4cd3272601_b.jpg
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1681/25274301993_c061073549_c.jpg
            display: https://c2.staticflickr.com/2/1681/25274301993_4c01a60848_o.jpg
      -
        id: nxmw-storyboard-06
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1689/25863792921_c9334810af_c.jpg
            display: https://c2.staticflickr.com/2/1689/25863792921_c9334810af_b.jpg
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1558/25937783045_8cf7188988_c.jpg
            display: https://c2.staticflickr.com/2/1558/25937783045_8cf7188988_b.jpg
      -
        id: nxmw-storyboard-07
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1583/25849869101_7cc65c1ddb_c.jpg
            display: https://c2.staticflickr.com/2/1583/25849869101_7cc65c1ddb_b.jpg
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1637/25306902624_364d6bb70d_c.jpg
            display: https://c2.staticflickr.com/2/1637/25306902624_364d6bb70d_b.jpg
      -
        id: nxmw-storyboard-08
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1545/25933042576_11e30ae404_c.jpg
            display: https://c2.staticflickr.com/2/1545/25933042576_11e30ae404_b.jpg
      -
        id: nxmw-storyboard-09
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1628/25933104106_c05dce6565_c.jpg
            display: https://c2.staticflickr.com/2/1628/25933104106_c05dce6565_b.jpg
      -
        id: nxmw-storyboard-10
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1518/26282191031_2fbb26bdcf_z.jpg
            display: https://c2.staticflickr.com/2/1518/26282191031_2fbb26bdcf_b.jpg
      -
        id: nxmw-storyboard-11
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1509/26348471935_8155fe948f_z.jpg
            display: https://c2.staticflickr.com/2/1509/26348471935_8155fe948f_b.jpg
      -
        id: nxmw-storyboard-12
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1588/25745783033_c32c2a4efe_z.jpg
            display: https://c2.staticflickr.com/2/1588/25745783033_c32c2a4efe_b.jpg
      -
        id: nxmw-storyboard-13
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1596/26348592895_128d634866_z.jpg
            display: https://c2.staticflickr.com/2/1596/26348592895_128d634866_b.jpg
      -
        id: nxmw-storyboard-14
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1709/25745924873_f23499332f_z.jpg
            display: https://c2.staticflickr.com/2/1709/25745924873_f23499332f_b.jpg
      -
        id: nxmw-storyboard-15
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1661/25743816034_c04995b824_z.jpg
            display: https://c2.staticflickr.com/2/1661/25743816034_c04995b824_b.jpg
      -
        id: nxmw-storyboard-16
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1620/25746047443_e77aa727af_z.jpg
            display: https://c2.staticflickr.com/2/1620/25746047443_e77aa727af_b.jpg
      -
        id: nxmw-storyboard-17
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1646/26075937270_24a18c8649_z.jpg
            display: https://c2.staticflickr.com/2/1646/26075937270_24a18c8649_b.jpg
      -
        id: nxmw-storyboard-18
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1543/25745082324_a35b4eb6a4_z.jpg
            display: https://c2.staticflickr.com/2/1543/25745082324_a35b4eb6a4_b.jpg
      -
        id: nxmw-storyboard-19
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1542/25747207243_8597b9f2b5_z.jpg
            display: https://c2.staticflickr.com/2/1542/25747207243_8597b9f2b5_b.jpg
      -
        id: nxmw-storyboard-20
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1487/26257661522_6a5fda6b75_z.jpg
            display: https://c2.staticflickr.com/2/1487/26257661522_6a5fda6b75_b.jpg
      -
        id: nxmw-storyboard-21
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1479/26350056965_cba339ddca_z.jpg
            display: https://c2.staticflickr.com/2/1479/26350056965_cba339ddca_b.jpg
      -
        id: nxmw-storyboard-22
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1485/26283892001_0b9f26551e_z.jpg
            display: https://c2.staticflickr.com/2/1485/26283892001_0b9f26551e_b.jpg
      -
        id: nxmw-storyboard-23
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1478/26077250710_925a70a61d_z.jpg
            display: https://c2.staticflickr.com/2/1478/26077250710_925a70a61d_b.jpg
concept_art:
  render: true
  list:
    -
      id: 10001
      name: Weird Dog
      description: |
        Working out the look of the pages. Tanned pages with some patina. Organic watercolor background with tight illustration over it.
      images:
        -
          orientation: landscape
          thumbnail: https://c2.staticflickr.com/2/1554/23911266843_b52a65c2db_z.jpg
          display: https://c2.staticflickr.com/2/1554/23911266843_4518f3dc55_o.jpg
reference_images:
  description: |
    - Childrens' book illustration styles
    - Color palletes
    - Visual Reference Photos
    - texture
    - paper color
  list:
    -
      id: reference_image001
      orientation: landscape
      url: http://rlv.zcache.com/svc/view?rlvnet=1&realview=113443160207323201&design=be63eedf-779d-426a-bb92-b54368293bd8&type=standard_postcard&max_dim=1024&hide=bleed%2Csafe%2CvisibleMask&r=1452348328459
      note: |
        looks like illustration from the 1800s but updated to have a comic book style.

        desaturated, contrast lowered. there is no 100% black which is why the tiger's back leg works so well

        [source](http://www.zazzle.com/tiger_alphabet_postcard-239475347601651440)
    -
      id: reference_image010
      orientation: landscape
      url: http://rlv.zcache.com/svc/view?rlvnet=1&realview=113805996568903071&design=a53f2976-e509-4db8-b427-66fef5b6f108&style=20x14&max_dim=1024&hide=bleed%2Csafe%2CvisibleMask&r=1452348447885
      note: |
        better palette than previous one
    -
      id: reference_image002
      orientation: landscape
      url: http://rlv.zcache.com/svc/view?rlvnet=1&realview=113805996568903071&design=095a08fc-149e-4ee5-a30a-4337a18731f4&style=20x14&max_dim=1024&hide=bleed%2Csafe%2CvisibleMask&r=1452344565049
      note: |
        see prev
    -
      id: reference_image003
      orientation: portrait
      url: http://rlv.zcache.com/svc/view?rlvnet=1&realview=113381087925757000&design=0a205344-4108-4971-9a58-a2f66b73844f&size=%5B16.0000%2C20.3636%5D&media=value_posterpaper_matte&max_dim=1024&hide=bleed%2Csafe%2CvisibleMask&r=1452344673673
      note: |
        see prev.

        nice texture
    -
      id: reference_image004
      orientation: portrait
      url: http://s3images.coroflot.com/user_files/individual_files/182303_i78szb47StIOqE6mbTzVUimtE.jpg
      note: |
        line work, color pallete
    -
      id: reference_image005
      orientation: portrait
      url: http://56.media.tumblr.com/b2da11859252ab18dbf98991382e0db8/tumblr_nzoc1sGG0l1qz9v0to5_1280.jpg
      note: |
        color pallete, line work
    -
      id: reference_image006
      orientation: landscape
      url: http://www.neatorama.com/wp-content/uploads/2009/11/best-7-600.jpg
      note: |
        color pallete
    -
      id: reference_image007
      orientation: landscape
      url: http://paintersoflouisville.com/wp-content/uploads/2013/10/where-the-wild-things-are-illustrations1.jpg
      note: |
        line work
    -
      id: reference_image008
      orientation: landscape
      url: http://tutorial9.s3.amazonaws.com/uploads/2009/03/children-bookillustration.jpg
      note: |
        commposition, line work. Use of bold black areas.
    -
      id: reference_image009
      orientation: landscape
      url: http://digital-art-gallery.com/oid/22/1000x729_5654_Dino_and_schoolgirl_2d_illustration_book_dinosaur_children_watercolor_trex_picture_image_digital_art.jpg
      note: |
        commposition, line work.

        The natural frame created by the watercolor.
    -
      id: reference_image011
      orientation: portrait
      url: https://s-media-cache-ak0.pinimg.com/736x/91/b2/37/91b237612394a415db044dd355312f0f.jpg
      note: |
        Nice color palette. Too realistic, but good colors.
    -
      id: reference_image012
      orientation: landscape
      url: http://56.media.tumblr.com/0795570a334b26e4f7890f868e0c66b1/tumblr_mou416EDkr1sva8ejo1_500.jpg
      note: |
        line work, color palette.

        [source](http://artistsanimals.tumblr.com/post/54186425339/artist-a-weisgerber-book-illustration-from)
