name: North By Midwest
description: |
  A story about a Jackass
characters:
  render: true
  description: |
    The characters
  list:
    -
      id: jackass
      name: Jackass
      occupation: Plumber
      role: lead
      images:
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5755/22569031093_aeb7dbdbe3.jpg
          display: https://c2.staticflickr.com/6/5755/22569031093_aeb7dbdbe3_b.jpg
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5738/23196101915_c185d909b3.jpg
          display: https://c2.staticflickr.com/6/5738/23196101915_c185d909b3_b.jpg
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5631/22828141069_76e4885915.jpg
          display: https://c2.staticflickr.com/6/5631/22828141069_76e4885915_b.jpg
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/1/763/22569031513_86013833e4.jpg
          display: https://c1.staticflickr.com/1/763/22569031513_86013833e4_b.jpg
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/1/626/22569031703_935c0752f9.jpg
          display: https://c1.staticflickr.com/1/626/22569031703_935c0752f9_b.jpg
      description: |
        Jackass is the lead character. He's not dopey, but he is naïve somewhat.
    -
      id: fanny
      name: Fanny
      occupation: Bartender
      role: lead
      images:
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/1/757/22567619524_b18acc8320.jpg
          display: https://c1.staticflickr.com/1/757/22567619524_b18acc8320_b.jpg
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/1/675/22900306400_6c1e9e7b72.jpg
          display: https://c1.staticflickr.com/1/675/22900306400_6c1e9e7b72_b.jpg
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/1/604/23196102435_5936421e7f.jpg
          display: https://c1.staticflickr.com/1/604/23196102435_5936421e7f_b.jpg
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5755/23170008876_c40bd5638f.jpg
          display: https://c2.staticflickr.com/6/5755/23170008876_c40bd5638f_b.jpg
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5655/23196102585_1b82cb21c3.jpg
          display: https://c2.staticflickr.com/6/5655/23196102585_1b82cb21c3_b.jpg
      description: |
        She a gold digger
resources: >

  * [Original PDF of the book from Jon](https://drive.google.com/open?id=0B3I1UYm_FEJrajF2d1pSMTM2MzQ)

  * myscriptfont.com for the text
storyboards:
  -
    name: Book 01
    boards:
      -
        id: nxmw-storyboard-01
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1528/23572486563_003da5f7d0.jpg
            display: https://c2.staticflickr.com/2/1528/23572486563_b097f00f8d_k.jpg
      -
        id: nxmw-storyboard-02
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1445/23831478379_8e42bded7c.jpg
            display: https://c2.staticflickr.com/2/1445/23831478379_de72764e1b_k.jpg
      -
        id: nxmw-storyboard-03
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1557/23903697090_fc902c6e57.jpg
            display: https://c2.staticflickr.com/2/1557/23903697090_06a0f2131f_k.jpg
      -
        id: nxmw-storyboard-04
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1705/23571106444_b6d37fb94b.jpg
            display: https://c2.staticflickr.com/2/1705/23571106444_63a51cac53_k.jpg
      -
        id: nxmw-storyboard-05
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1530/23831477949_e9c1620104.jpg
            display: https://c2.staticflickr.com/2/1530/23831477949_3cd6671847_k.jpg
      -
        id: nxmw-storyboard-06
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1621/23903696560_f0258d08e7.jpg
            display: https://c2.staticflickr.com/2/1621/23903696560_a6b10d82fa_k.jpg
      -
        id: nxmw-storyboard-07
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1566/23831477699_588ceb450f.jpg
            display: https://c2.staticflickr.com/2/1566/23831477699_ed9173eaf5_k.jpg
      -
        id: nxmw-storyboard-08
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1662/24173192536_8cd1cebe4b.jpg
            display: https://c2.staticflickr.com/2/1662/24173192536_682735565f_k.jpg
      -
        id: nxmw-storyboard-09
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1649/23903696290_296fe980f8.jpg
            display: https://c2.staticflickr.com/2/1649/23903696290_bd4ebe9671_k.jpg
      -
        id: nxmw-storyboard-10
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1450/24199280435_4b1e785e54.jpg
            display: https://c2.staticflickr.com/2/1450/24199280435_ea94a0a4ce_k.jpg
      -
        id: nxmw-storyboard-11
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1475/23572485583_4a614cb033.jpg
            display: https://c2.staticflickr.com/2/1475/23572485583_a0bc294316_k.jpg
      -
        id: nxmw-storyboard-12
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1579/24116704951_f6096d6c38.jpg
            display: https://c2.staticflickr.com/2/1579/24116704951_5962127d4d_k.jpg
      -
        id: nxmw-storyboard-13
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1648/24116704701_2ddf0243ea.jpg
            display: https://c2.staticflickr.com/2/1648/24116704701_1f7a771d2f_k.jpg
      -
        id: nxmw-storyboard-14
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1584/24173191726_1f7bf7b7b5.jpg
            display: https://c2.staticflickr.com/2/1584/24173191726_400b03381d_k.jpg
      -
        id: nxmw-storyboard-15
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1522/24091246882_116330d561.jpg
            display: https://c2.staticflickr.com/2/1522/24091246882_92dd6f9bc8_k.jpg
      -
        id: nxmw-storyboard-16
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1600/23831476379_cb77e653b9.jpg
            display: https://c2.staticflickr.com/2/1600/23831476379_e683bb01a6_k.jpg
      -
        id: nxmw-storyboard-17
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1473/23572484273_a660ee5b3b.jpg
            display: https://c2.staticflickr.com/2/1473/23572484273_f906e0ba45_k.jpg
      -
        id: nxmw-storyboard-18
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1603/24091246222_008cb9ed5e.jpg
            display: https://c2.staticflickr.com/2/1603/24091246222_57a49e8a11_k.jpg
      -
        id: nxmw-storyboard-19
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1688/24173190796_a3550c6582.jpg
            display: https://c2.staticflickr.com/2/1688/24173190796_464f47dc6e_k.jpg
      -
        id: nxmw-storyboard-20
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1494/24199278865_ffc90eb2cd.jpg
            display: https://c2.staticflickr.com/2/1494/24199278865_d6be993677_k.jpg
      -
        id: nxmw-storyboard-21
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1456/23831475699_a168f33e6b.jpg
            display: https://c2.staticflickr.com/2/1456/23831475699_912175d606_k.jpg
      -
        id: nxmw-storyboard-22
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1601/23831475519_dd58538778.jpg
            display: https://c2.staticflickr.com/2/1601/23831475519_2284ff9300_k.jpg
      -
        id: nxmw-storyboard-23
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1471/23903694100_f4d2177a77.jpg
            display: https://c2.staticflickr.com/2/1471/23903694100_399881d435_k.jpg
      -
        id: nxmw-storyboard-24
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1597/24199278275_a2bb30e576.jpg
            display: https://c2.staticflickr.com/2/1597/24199278275_06497f8aa3_k.jpg
      -
        id: nxmw-storyboard-25
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1479/23571103454_5ba4f0d343.jpg
            display: https://c2.staticflickr.com/2/1479/23571103454_cce55afe76_k.jpg
      -
        id: nxmw-storyboard-26
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1666/24173189516_a20afb8cb1.jpg
            display: https://c2.staticflickr.com/2/1666/24173189516_bd1ab1ca60_k.jpg
      -
        id: nxmw-storyboard-27
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1511/23572482753_ae2da30e59.jpg
            display: https://c2.staticflickr.com/2/1511/23572482753_a325f28c9f_k.jpg
      -
        id: nxmw-storyboard-28
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1513/24173189196_5abfd12aa5.jpg
            display: https://c2.staticflickr.com/2/1513/24173189196_0439974754_k.jpg
      -
        id: nxmw-storyboard-29
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1640/23571102664_7df36f3b35.jpg
            display: https://c2.staticflickr.com/2/1640/23571102664_d4010d3759_k.jpg
      -
        id: nxmw-storyboard-30
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1635/23903692970_58fee75b91.jpg
            display: https://c2.staticflickr.com/2/1635/23903692970_b845e51304_k.jpg
      -
        id: nxmw-storyboard-31
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1488/24199277115_241d152746.jpg
            display: https://c2.staticflickr.com/2/1488/24199277115_687b52c16a_k.jpg
      -
        id: nxmw-storyboard-32
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1496/24116701211_d5417d4344.jpg
            display: https://c2.staticflickr.com/2/1496/24116701211_bcb7b17dcc_k.jpg
      -
        id: nxmw-storyboard-33
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1562/23903692420_0dbdecfb69.jpg
            display: https://c2.staticflickr.com/2/1562/23903692420_707e183cfd_k.jpg
      -
        id: nxmw-storyboard-34
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1620/24116701001_96eea5c943.jpg
            display: https://c2.staticflickr.com/2/1620/24116701001_689f2a1657_k.jpg
      -
        id: nxmw-storyboard-35
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1459/23903691880_ae62900f24.jpg
            display: https://c2.staticflickr.com/2/1459/23903691880_e9534ebb2f_k.jpg
      -
        id: nxmw-storyboard-36
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1583/24173187746_6a0c699898.jpg
            display: https://c2.staticflickr.com/2/1583/24173187746_1c8d4c618c_k.jpg
      -
        id: nxmw-storyboard-37
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1699/23571101344_dbb12dbfb0.jpg
            display: https://c2.staticflickr.com/2/1699/23571101344_9415ea8cbe_k.jpg
      -
        id: nxmw-storyboard-38
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1529/23571101214_fa555c8519.jpg
            display: https://c2.staticflickr.com/2/1529/23571101214_95512f758b_k.jpg
      -
        id: nxmw-storyboard-39
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1471/23831472909_84cb1d8821.jpg
            display: https://c2.staticflickr.com/2/1471/23831472909_6538d196f8_k.jpg
      -
        id: nxmw-storyboard-40
        images:
          -
            orientation: landscape
            thumbnail: https://c2.staticflickr.com/2/1524/24091242722_74beb03ca3.jpg
            display: https://c2.staticflickr.com/2/1524/24091242722_9c330cd661_k.jpg
reference_images:
  description: |
    - Childrens' book illustration styles
    - Color palletes
    - Visual Reference Photos
  list:
    -
      orientation: portrait
      url: http://56.media.tumblr.com/b2da11859252ab18dbf98991382e0db8/tumblr_nzoc1sGG0l1qz9v0to5_1280.jpg
      note: |
        muted colors, line work
