canvas:
    id: cabo
    dimensions:
        width: 5760
        height: 2000
elements:
    -
        id: ear_herpes_center_building
        tag: image
        src: /img/layout/cabo/ear_herpes_center_building.png
        position:
            left: 24
            top: 87
        dimensions:
            width: 600
            height: auto
        parallax_x:
            depth: 20
        parallax_y:
            depth: 20

    -
        id: ear_herpes_center_cat
        tag: image
        src: /img/layout/cabo/ear_herpes_center_cat.png
        position:
            left: 78
            top: 494
        dimensions:
            width: 551
            height: auto
        parallax_x:
            depth: 16
        parallax_y:
            depth: 16
