export const GET_CONTENT_ARTICLE_REQUEST = 'GET_CONTENT_ARTICLE_REQUEST';
export const GET_CONTENT_ARTICLE_ERROR = 'GET_CONTENT_ARTICLE_ERROR';
export const GET_CONTENT_ARTICLE_SUCCESS = 'GET_CONTENT_ARTICLE_SUCCESS';
export const POST_CONTENT_ARTICLE_REQUEST = 'POST_CONTENT_ARTICLE_REQUEST';
export const POST_CONTENT_ARTICLE_ERROR = 'POST_CONTENT_ARTICLE_ERROR';
export const POST_CONTENT_ARTICLE_SUCCESS = 'POST_CONTENT_ARTICLE_SUCCESS';
export const PUT_CONTENT_ARTICLE_REQUEST = 'PUT_CONTENT_ARTICLE_REQUEST';
export const PUT_CONTENT_ARTICLE_ERROR = 'PUT_CONTENT_ARTICLE_ERROR';
export const PUT_CONTENT_ARTICLE_SUCCESS = 'PUT_CONTENT_ARTICLE_SUCCESS';
export const RESET_CONTENT_ARTICLE = 'RESET_CONTENT_ARTICLE';

export const GET_CONTENT_ARTICLES_REQUEST = 'GET_CONTENT_ARTICLES_REQUEST';
export const GET_CONTENT_ARTICLES_ERROR = 'GET_CONTENT_ARTICLES_ERROR';
export const GET_CONTENT_ARTICLES_SUCCESS = 'GET_CONTENT_ARTICLES_SUCCESS';
