export const LOGIN_ATTEMPT = {
    REQUEST: "LOGIN_ATTEMPT_REQUEST",
    ERROR: "LOGIN_ATTEMPT_ERROR",
    SUCCESS: "LOGIN_ATTEMPT_SUCCESS"
};

export const CHARACTER = {
    REQUEST: "CHARACTER_REQUEST",
    ERROR: "CHARACTER_ERROR",
    SUCCESS: "CHARACTER_SUCCESS"
};
