export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST';
export const GET_PROJECT_ERROR = 'GET_PROJECT_ERROR';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';

export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';

export const GET_STORYBOARD_REQUEST = 'GET_STORYBOARD_REQUEST';
export const GET_STORYBOARD_ERROR = 'GET_STORYBOARD_ERROR';
export const GET_STORYBOARD_SUCCESS = 'GET_STORYBOARD_SUCCESS';
