export const UI_STATE_INITIALIZING = 'INITIALIZING';
export const UI_STATE_REQUESTING = 'REQUESTING';
export const UI_STATE_ERROR = 'ERROR';
export const UI_STATE_SUCCESS = 'SUCCESS';
export const UI_STATE_COMPLETE = 'COMPLETE';

export const FLICKR_SELECTOR_STATE_INITIALIZING = 'INITIALIZING';
export const FLICKR_SELECTOR_STATE_REQUESTING = 'REQUESTING';
export const FLICKR_SELECTOR_STATE_ERROR = 'ERROR';
export const FLICKR_SELECTOR_STATE_SUCCESS = 'SUCCESS';
export const FLICKR_SELECTOR_STATE_COMPLETE = 'COMPLETE';
