canvas:
    id: uncles
    background_color: '#CCC'
    dimensions:
        width: 5760
        height: 1080
    type: phaser
    # input: cursor|flick
    input:
        - cursor
elements:
    -
        id: uncle001
        type: image
        src: /img/layout/uncles/uncle001.png
        position:
            left: 727
            top: 175
        dimensions:
            width: 150
            height: auto
    -
        id: uncle002
        type: image
        src: /img/layout/uncles/uncle002.png
        position:
            left: 80
            top: 208
        dimensions:
            width: 400
            height: auto
    -
        id: uncle003
        type: image
        src: /img/layout/uncles/uncle003.png
        position:
            left: 920
            top: 208
        dimensions:
            width: 400
            height: auto
