canvas:
    id: graphics001
    background_color: '#5B1234'
    dimensions:
        width: 3840
        height: 1080
    type: phaser
    camera:
      speed_x: 4
      speed_y: 4
      upper_bound_y: 50
      lower_bound_y: 0
    # input: cursor|flick
    input:
        - cursor
elements:
    -
        id: raindrop
        type: emitter
        src: /img/layout/shopping/raindrop.png
        position:
            left: world_center
            top: 0
        dimensions:
            width: game_width
        emitter:
          explode: false
          frequency: 0.1
          lifespan: 5000
          quantity: 0
          max_particles: 2000
          min_rotation: 52
          max_rotation: 55
          min_particle_scale: 0.3
          max_particle_scale: 0.9
          min_y_speed: 500
          max_y_speed: 600
          min_x_speed: -600
          max_x_speed: -500
    -
        id: balloon_hands_man
        type: image
        src: /img/layout/cabo/balloon_hands_man.png
        position:
            left: 850
            top: 700
        dimensions:
            width: 3840
            height: auto
        layer:
            layer_id: foreground
    -
        id: balloon_hands_man2
        type: image
        src: /img/layout/cabo/balloon_hands_man.png
        position:
            left: 1250
            top: 400
        dimensions:
            width: 280
            height: auto
        animations:
            - 
                type: sin_wobble
                properties:
                    distance_x: 30
                    slice_height: 4
        layer:
            layer_id: background
    -
        id: uncle003
        type: image
        src: /img/layout/uncles/uncle003.png
        position:
            left: 920
            top: 208
        dimensions:
            width: 400
            height: auto
        layer:
            layer_id: background
    -
        id: uncle001
        type: image
        src: /img/layout/uncles/uncle001.png
        position:
            left: 727
            top: 175
        dimensions:
            width: 150
            height: auto
        layer:
            layer_id: background
    -
        id: testmask
        type: image
        src: /img/layout/shopping/testmask.png
        position:
            left: 0
            top: 0
        dimensions:
            width: 3840
            height: auto
        layer:
            layer_id: foreground
layers:
  -
    id: background
    size_scale: 1
    motion_scale: .1
  -
    id: foreground
    size_scale: 1
    motion_scale: .8