instagram:
  client_id: "a6c4e37cd91b4020a09a74a40cf836d6"
  user_id: 31264453
comics:
  tweetstream-and-zeitgeist:
    title: "Tweetstream and Zeitgeist in: On the Scene!"
    parts:
      -
        title: "Part 1/3"
        panels:
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-1/01.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-1/02.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-1/03.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-1/04.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-1/05.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-1/06.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-1/07.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-1/08.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-1/the_end.jpg"
      -
        title: "Part 2/3"
        panels:
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-2/01.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-2/02.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-2/03.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-2/04.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-2/05.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-2/06.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-2/07.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-2/08.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-2/09.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-2/the_end2.jpg"
      -
        title: "Part 3/3"
        panels:
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-3/01.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-3/02.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-3/03.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-3/04.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-3/05.jpg"
          - "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-3/the_end3.jpg"
portfolio:
    category:
        -
            id: illustration
            name: "Illustration"
        -
            id: animation
            name: "Animation"
        -
            id: comic
            name: "Comic"
        -
            id: print_design
            name: "Print Design"
        -
            id: webdev
            name: "Web Development / Design"
        -
            id: character_design
            name: "Character Design"
        -
            id: instagram
            name: "Instagram"
    gallery:
        -
            title: "Sauced Octopus"
            year: "2008"
            medium: "pencil, Painter, Photoshop"
            category_id: illustration
            type: "image"
            content: "https://farm3.staticflickr.com/2473/3692721420_0cee6cd9d2_b.jpg"
            thumbnail: "https://c1.staticflickr.com/3/2473/3692721420_0cee6cd9d2.jpg"
            description: "Just an illustration I used to sell prints of."
        -
            title: "Discommunication"
            year: "2010"
            medium: "Painter"
            category_id: illustration
            type: "image"
            content: "https://c1.staticflickr.com/5/4040/4537442530_55219acf71_b.jpg"
            thumbnail: "https://c1.staticflickr.com/5/4040/4537442530_55219acf71.jpg"
            description: "Can't ever figure anything out, there are holes in the story."
        -
            title: "Late Again"
            year: "2007"
            medium: "pencil, Painter"
            category_id: illustration
            type: "image"
            content: "https://c2.staticflickr.com/2/1416/1433569514_27d34287f5_o.jpg"
            thumbnail: "https://c2.staticflickr.com/2/1416/1433569514_957f7e790f.jpg"
            description: "Can't get there on time and don't want to."
        -
            title: "a pungent seasonal realization"
            year: "2007"
            medium: "pencil, ink, Painter, Photoshop"
            category_id: illustration
            type: "image"
            content: "https://c1.staticflickr.com/3/2213/1871848485_c42eae1fc2_b.jpg"
            thumbnail: "https://c1.staticflickr.com/3/2213/1871848485_c42eae1fc2.jpg"
            description: "white knuckling in the white snow"
        -
            title: "It's a Mix Tape I Might Eat"
            year: "2007"
            medium: "pencil, Painter, Photoshop"
            category_id: illustration
            type: "image"
            content: "https://c2.staticflickr.com/2/1177/954455978_e1b3840227_o.jpg"
            thumbnail: "https://c2.staticflickr.com/2/1177/954455978_dc9c5788a8.jpg"
            description: "It says please meatball me."
        -
            title: "-+-"
            year: "2008"
            medium: "pencil, Painter, Photoshop"
            category_id: illustration
            type: "image"
            content: "https://c2.staticflickr.com/4/3254/2982520659_4cfd90fae8_b.jpg"
            thumbnail: "https://c2.staticflickr.com/4/3254/2982520659_4cfd90fae8.jpg"
            description: "burping colors"
        -
            title: "room temperature wheels"
            year: "2009"
            medium: "pencil, Painter, Photoshop"
            category_id: illustration
            type: "image"
            content: "https://c2.staticflickr.com/4/3480/4003621695_39ea3147ef_b.jpg"
            thumbnail: "https://c2.staticflickr.com/4/3480/4003621695_39ea3147ef.jpg"
            description: "a boy's life"
        -
            title: "get outta my dreams and into my van"
            year: "2009"
            medium: "pencil, Painter, Photoshop"
            category_id: illustration
            type: "image"
            content: "https://c1.staticflickr.com/3/2768/4065908510_73aaac4dcc_b.jpg"
            thumbnail: "https://c1.staticflickr.com/3/2768/4065908510_73aaac4dcc.jpg"
            description: "beats van"
        -
            title: "Atomic Cigarette"
            year: "2010"
            medium: "pencil, Painter, Photoshop"
            category_id: illustration
            type: "image"
            content: "https://c1.staticflickr.com/5/4026/4537442840_e015dfcb1c_b.jpg"
            thumbnail: "https://c1.staticflickr.com/5/4026/4537442840_e015dfcb1c.jpg"
            description: "last cigarette on earth"
        -
            title: "the octopus is the dialogue"
            year: "2008"
            medium: "Painter"
            category_id: illustration
            type: "image"
            content: "https://c1.staticflickr.com/3/2107/2488224137_b1d880813b_b.jpg"
            thumbnail: "https://c1.staticflickr.com/3/2107/2488224137_b1d880813b.jpg"
            description: "we only exist by communitcating with another"
        -
            title: "makin it with bots"
            year: "2007"
            medium: "Painter"
            category_id: illustration
            type: "image"
            content: "https://c2.staticflickr.com/2/1037/1342558150_29469a9419_o.jpg"
            thumbnail: "https://c2.staticflickr.com/2/1037/1342558150_5924d53037.jpg"
            description: "creation and destruction with the stroke of a brush"
        -
            title: "Cute Animals (animatic)"
            year: "2007"
            medium: "pencil, Photoshop, Flash"
            category_id: animation
            type: "embed"
            content: >
              <iframe width="900" height="504" src="https://www.youtube.com/embed/iRTw-bKBIeI" frameborder="0" allowfullscreen></iframe>
            thumbnail: "http://img.youtube.com/vi/iRTw-bKBIeI/mqdefault.jpg"
            description: "An animatic for the song \"Cute Animals\" by Gary Wertz. https://www.youtube.com/embed/iRTw-bKBIeI"
        -
            title: "Eyeguy Animation Test"
            year: "2007"
            medium: "pencil, Painter, Photoshop, Flash"
            category_id: animation
            type: "embed"
            content: >
              <iframe width="900" height="504" src="https://www.youtube.com/embed/MVC4mg46haM" frameborder="0" allowfullscreen></iframe>
            thumbnail: "http://img.youtube.com/vi/MVC4mg46haM/0.jpg"
            description: "A character test for Eyeguy at the office. https://www.youtube.com/watch?v=MVC4mg46haM"
        -
            title: "Tweetstream and Zeitgeist in: On the Scene"
            year: "2014"
            medium: "Painter"
            category_id: comic
            type: "image"
            content: "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-1/02.jpg"
            thumbnail: "https://c2.staticflickr.com/6/5814/22237250364_1932310813.jpg"
            description: >
              Twitter and Google have their own superheroes - Tweetstream and Zeitgeist, respectively.
              <a href="/comics/tweetstream-and-zeitgeist" target="_blank">View</a>
        -
            title: "masthead for learning to experiment blog"
            year: "2009"
            medium: "Painter"
            category_id: illustration
            type: "image"
            content: "https://farm4.staticflickr.com/3419/3918604896_948bb5fb23_b.jpg"
            thumbnail: "https://c2.staticflickr.com/4/3419/3918604896_948bb5fb23.jpg"
            description: "A masthead for a friend's cooking blog"
        -
            title: "audio van gogh - driving music (cd insert inside)"
            year: "2004"
            medium: "Maya, Photoshop, InDesign"
            category_id: print_design
            type: "image"
            content: "https://farm4.staticflickr.com/3200/2852136437_6aa93fa9bc_o.jpg"
            thumbnail: "https://c2.staticflickr.com/4/3200/2852136437_c966b31ef3.jpg"
            description: "CD insert art for artist Audio Van Gogh"
        -
            title: "CD Album art |  Routine Life by John hRuby"
            year: "2009"
            medium: "Photography, Illustrator, Photoshop"
            category_id: print_design
            type: "image"
            content: "https://farm5.staticflickr.com/4041/4211926998_89a464b489_b.jpg"
            thumbnail: "https://c1.staticflickr.com/5/4041/4211926998_89a464b489.jpg"
            description: "CD case cover for album by John Hruby http://www.iheart.com/artist/john-hruby-288206/"
        -
            title: "My Mango Tango Book Cover"
            year: "2011"
            medium: "Painter, Photoshop, Illustrator"
            category_id: print_design
            type: "image"
            content: "https://farm8.staticflickr.com/7130/7751591522_8dcca9f7ed_b.jpg"
            thumbnail: "https://c1.staticflickr.com/7/6158/6195612026_391c54cdb4.jpg"
            description: "A book cover for author Nisha Mathur about an indian woman assimilating in the US."
        -
            title: "The Dwarves Website"
            year: "2006"
            medium: "Photoshop, Dreamweaver, Wordpress, PHP, MySQL, HTML, Flash, Javascript, CSS"
            category_id: webdev
            type: "image"
            content: "https://farm4.staticflickr.com/3060/2852102371_9f5d32ba0e_o.jpg"
            thumbnail: "https://c2.staticflickr.com/4/3060/2852102371_3d7b5a5971.jpg"
            description: "Website for the Dwarves http://thedwarves.com\n* Image uploading with automatic resizing\n* \"Gallerain\" Flash/MySQL based image rotator\n* Integrated WordPress blog\n* Presskit Hi-res media uploads"
        -
            title: "Bandbajgayi.com"
            year: "2015"
            medium: "Photoshop, PHP, HTML, Javascript, CSS"
            category_id: webdev
            type: "image"
            content: "https://farm1.staticflickr.com/689/20249444023_21650c811e_b.jpg"
            thumbnail: "https://c1.staticflickr.com/1/689/20249444023_21650c811e.jpg"
            description: "This is my own wedding website which I designed with my wife :) -- fully functional feature-rich wedding website. I can make one for you. http://bandbajgayi.com"
        -
            title: "Beepo Takes A Pipe To Nowhere"
            year: "2010"
            medium: "pencil, Painter, Photoshop"
            category_id: illustration
            type: "image"
            content: "https://farm3.staticflickr.com/2439/3663515635_1c89de110c_b.jpg"
            thumbnail: "https://c1.staticflickr.com/3/2439/3663515635_1c89de110c.jpg"
            description: "Beepo is a robot built by Japanese robotics engineers with whatever information they had about Italian stereotypes. Upon his activation they uploaded the occupation \"plumber\" into his main fucking memory.\nIn this world there are no humans around but somehow he always has a pipe to clean out or something to unclog. It's a very septic life. He tends to drink and do a lot of drugs, even on the job.\nBut he also has a stereotypically Italian lust for life, and he sings Opera to all the beautiful women ... robots. Women robots.\nThis piece is concept art for a mini film starring the one and only Beepo Beeparelli"
        -
            title: "Burger Pope Ad"
            year: "2007"
            medium: "pencil, Painter, Photoshop"
            category_id: illustration
            type: "image"
            content: "https://farm2.staticflickr.com/1156/1467947071_28963a1d91_o.jpg"
            thumbnail: "https://c2.staticflickr.com/2/1156/1467947071_8a362db26e.jpg"
            description: "Burger Pope!"
        -
            title: "Beepo Concept Art"
            year: "2009"
            medium: "Painter"
            category_id: character_design
            type: "image"
            content: "https://farm3.staticflickr.com/2533/3996839316_699ee275b7_b.jpg"
            thumbnail: "https://c1.staticflickr.com/3/2533/3996839316_699ee275b7.jpg"
            description: "Character designs for Beepo Beeparelli"
        -
            title: "Beepo Doesn't Get Turtles"
            year: "2010"
            medium: "pencil"
            category_id: character_design
            type: "image"
            content: "https://farm3.staticflickr.com/2786/4326820558_3db6e6beee_b.jpg"
            thumbnail: "https://c1.staticflickr.com/3/2786/4326820558_3db6e6beee.jpg"
            description: "Character design for Beepo Beeparelli"
        -
            title: "Uranium 239 Pops"
            year: "1997"
            medium: "Painter"
            category_id: illustration
            type: "image"
            content: "https://farm1.staticflickr.com/175/461988892_d37e43bae6_o.jpg"
            thumbnail: "https://c1.staticflickr.com/1/175/461988892_6569620052.jpg"
            description: "Uranium 239 Glow Pops"
        -
            title: "The Power of Buddha Compels You"
            year: "2011"
            medium: "Painter"
            category_id: illustration
            type: "image"
            content: "https://c2.staticflickr.com/8/7002/6534378995_5b3528bbde_b.jpg"
            thumbnail: "https://c2.staticflickr.com/8/7002/6534378995_5b3528bbde.jpg"
            description: "you cannot resist"
        -
            title: "The way the sun moves"
            year: "2002"
            medium: "3D Studio, Painter"
            category_id: illustration
            type: "image"
            content: "https://c1.staticflickr.com/1/170/461995807_0298112583_o.jpg"
            thumbnail: "https://c1.staticflickr.com/1/170/461995807_fcbafed3f3.jpg"
            description: "a road trip"

instagrams:
  - "29N7rtRZv1"
  - "tcy7cYRZnx"
  - "380qewxZge"
  - "3uHYLuRZlb"
  - "yYZoXQRZkN"
  - "vc7IPSRZsn"
  - "5db319RZhm"
  - "5ABC-HRZqR"
  - "4PCa-pRZmZ"
  - "3wvYyjRZpd"
  - "yQ1lEuxZpN"
  - "yQTZCBRZrf"
  - "u5wbHzRZun"
  - "uR78SDRZtK"
  - "sYSmxvxZrg"
  - "sXDHZqxZvv"
  - "rsRCrlRZgo"
  - "rrz7KdRZpy"
  - "rZ9Yb5RZrp"
  - "pXWC2IRZj3"
  - "oUPK8VRZmh"
  - "kGPqj1xZhs"

tweets:
  - "175800300060409856"
  - "180488009832079361"
  - "178887690022952960"
  - "125270555170582529"
  - "484708370805313536"
  - "449610572758515712"
  - "336235368468856832"
  - "517053689144430593"
  - "240906118694596608"
  - "201170247078772737"
  - "317507453195542528"

wpposts:
  - 47
  - 116
  - 1
