server:
    hostname: :SERVER_HOSTNAME
email:
    daily_email:
        from: :EMAIL_DAILY_EMAIL_FROM
        from_name: :EMAIL_DAILY_EMAIL_FROM_NAME
        subject: :EMAIL_DAILY_EMAIL_SUBJECT
security:
    secret: :SECURITY_SECRET
mysql:
    host: :MYSQL_HOST
    database: :MYSQL_DATABASE
    user: :MYSQL_USER
    password: :MYSQL_PASSWORD
service:
    mercury_postlight:
        key: :MERCURY_POSTLIGHT_KEY
    flickr:
        key: :FLICKR_KEY
        secret: :FLICKR_SECRET
    gdrive:
        client_json_config_filename: gdrive_client.json
        thumbnail_cache_folder: cache/gdrive/thumbnails
    instagram:
        client_id: :INSTAGRAM_CLIENT_ID
        client_secret: :INSTAGRAM_CLIENT_SECRET
    spotify:
        client_id: :SPOTIFY_CLIENT_ID
        client_secret: :SPOTIFY_CLIENT_SECRET
    vimeo:
        client_key: :VIMEO_CLIENT_ID
        client_secret: :VIMEO_CLIENT_SECRET
