application:
    api_key: :APPLICATION_KEY
server:
    hostname: :SERVER_HOSTNAME
email:
    daily_email:
        from: :EMAIL_DAILY_EMAIL_FROM
        from_name: :EMAIL_DAILY_EMAIL_FROM_NAME
        subject: :EMAIL_DAILY_EMAIL_SUBJECT
security:
    secret: :SECURITY_SECRET
mysql:
    host: :MYSQL_HOST
    database: :MYSQL_DATABASE
    user: :MYSQL_USER
    password: :MYSQL_PASSWORD
service:
    mercury_postlight:
        key: :MERCURY_POSTLIGHT_KEY
    pocket:
        key: :POCKET_KEY
    flickr:
        key: :FLICKR_KEY
        secret: :FLICKR_SECRET
    gdrive:
        client_json_config_filename: gdrive_client.json
        thumbnail_cache_folder: cache/gdrive/thumbnails
    instagram:
        client_id: :INSTAGRAM_CLIENT_ID
        client_secret: :INSTAGRAM_CLIENT_SECRET
    spotify:
        client_id: :SPOTIFY_CLIENT_ID
        client_secret: :SPOTIFY_CLIENT_SECRET
    vimeo:
        client_key: :VIMEO_CLIENT_ID
        client_secret: :VIMEO_CLIENT_SECRET
example:
    fountain:
        snippet: |
            **FADE IN:**

            A RIVER.

            We're underwater, watching a fat catfish swim along.

            This is The Beast.

            EDWARD (V.O.)
            There are some fish that cannot be caught.  It's not that they're faster or stronger than other fish.  They're just touched by something extra.  Call it luck.  Call it grace.  One such fish was The Beast.

            The Beast's journey takes it past a dangling fish hook, baited with worms.  Past a tempting lure, sparkling in the sun.  Past a swiping bear claw.  The Beast isn't worried.

            EDWARD (V.O.)(CONT'D)
            By the time I was born, he was already a legend.  He'd taken more hundred-dollar lures than any fish in Alabama. Some said that fish was the ghost of Henry Walls, a thief who'd drowned in that river 60 years before.   Others claimed he was a lesser dinosaur, left over from the Cretaceous period.

            INT.  WILL'S BEDROOM - NIGHT (1973)

            WILL BLOOM, AGE 3, listens wide-eyed as his father EDWARD BLOOM, 40's and handsome, tells the story.  In every gesture, Edward is bigger than life, describing each detail with absolute conviction.

            EDWARD
            I didn't put any stock into such speculation or superstition.  All I knew was I'd been trying to catch that fish since I was a boy no bigger than you.
            (closer)
            And on the day you were born, that was the day I finally caught him.

            EXT.  CAMPFIRE - NIGHT (1977)

            A few years later, and Will sits with the other INDIAN GUIDES as Edward continues telling the story to the tribe.

            EDWARD
            Now, I'd tried everything on it:  worms, lures, peanut butter, peanut butter-and-cheese.  But on that day I had a revelation:  if that fish was the ghost of a thief, the usual bait wasn't going to work.  I would have to use something he truly desired.

            Edward points to his wedding band, glinting in the firelight.

            LITTLE BRAVE
            (confused)
            Your finger?

            Edward slips his ring off.
