security:
    secret: :SECURITY_SECRET
mysql:
    host: :MYSQL_HOST
    database: :MYSQL_DATABASE
    user: :MYSQL_USER
    password: :MYSQL_PASSWORD
service:
    pocket:
        consumer_key: :POCKET_CONSUMER_KEY
sql:
    users:
        # authorization query
        select_by_username_and_password: |
            SELECT id, email, username
            FROM `users`
            WHERE username = :username
            AND password = :password
        # insert-update pocket account
        insert_update_pocket: |
            INSERT INTO user_account_pocket
            (user_id, username, access_token, date_added, date_updated)
            VALUES
            (:user_id, :username, :access_token, NOW(), NOW())
                ON DUPLICATE KEY UPDATE access_token = :access_token, date_updated = NOW()
