server:
    hostname: :SERVER_HOSTNAME
security:
    secret: :SECURITY_SECRET
api:
    base_url: :API_BASE_URL
service:
    pocket:
        key: :POCKET_KEY
    todoist:
        key: :TODOIST_KEY
        secret: :TODOIST_SECRET
    wunderlist:
        key: :WUNDERLIST_KEY
        secret: :WUNDERLIST_SECRET
