security:
    secret: "P1zzaP4rty!!!"
mysql:
    host: localhost
    database: explosio_likedrop-dev
    user: explosio_root
    password: uranium239
sql:
    users:
        # authorization query
        select_by_username_and_password: |
            SELECT id, email
            FROM `users`
            WHERE username = :username
            AND password = :password
