server:
    hostname: :SERVER_HOSTNAME
email:
    daily_email:
        from: :EMAIL_DAILY_EMAIL_FROM
        from_name: :EMAIL_DAILY_EMAIL_FROM_NAME
        subject: :EMAIL_DAILY_EMAIL_SUBJECT
security:
    secret: :SECURITY_SECRET
mysql:
    host: :MYSQL_HOST
    database: :MYSQL_DATABASE
    user: :MYSQL_USER
    password: :MYSQL_PASSWORD
service:
    pocket:
        consumer_key: :POCKET_CONSUMER_KEY
    gdrive:
        # filename of the .json file that the google client needs to work
        client_json_config_filename: gdrive_client.json
        thumbnail_cache_folder: cache/gdrive/thumbnails
    instagram:
        client_id: :INSTAGRAM_CLIENT_ID
        client_secret: :INSTAGRAM_CLIENT_SECRET
sql:
    users:
        # get all
        get_all: |
            SELECT id, username, email FROM users ORDER BY id
        # get by id
        get_by_id: |
            SELECT id, username, email FROM users WHERE id = :id
        # authorization query
        select_by_username_and_password: |
            SELECT id, email, username
            FROM `users`
            WHERE username = :username
            AND password = :password
    account_instagram:
        # insert-update instagram account
        insert_update_instagram_user: |
            INSERT INTO account_instagram
            (user_id, access_token, date_added, date_updated)
            VALUES
            (:user_id, :access_token, NOW(), NOW())
                ON DUPLICATE KEY UPDATE access_token = :access_token, date_updated = NOW()
        get_all: |
            SELECT * FROM account_instagram
        get_by_user_id: |
            SELECT * FROM account_instagram WHERE user_id = :user_id
    account_pocket:
        # insert-update pocket account
        insert_update_pocket_user: |
            INSERT INTO account_pocket
            (user_id, username, access_token, date_added, date_updated)
            VALUES
            (:user_id, :username, :access_token, NOW(), NOW())
                ON DUPLICATE KEY UPDATE access_token = :access_token, date_updated = NOW()
        get_all: |
            SELECT * FROM account_pocket
        get_by_user_id: |
            SELECT * FROM account_pocket WHERE user_id = :user_id
    account_gdrive:
        # insert-update gdrive account
        insert_update_gdrive_user: |
            INSERT INTO account_gdrive
            (user_id, access_token, refresh_token, date_added, date_updated)
            VALUES
            (:user_id, :access_token, :refresh_token, NOW(), NOW())
                ON DUPLICATE KEY UPDATE access_token = :access_token, refresh_token = :refresh_token, date_updated = NOW()
        get_all: |
            SELECT * FROM account_gdrive
        get_by_user_id: |
            SELECT * FROM account_gdrive WHERE user_id = :user_id
    content_pocket:
        insert_update_pocket_content_for_user: |
            INSERT INTO content_pocket
            (account_pocket_id, user_id, item_id, json, date_added, date_updated)
            VALUES
            (:account_pocket_id, :user_id, :item_id, :json, :date_added, :date_updated)
                ON DUPLICATE KEY UPDATE json = :json, date_updated = :date_updated
        delete_content_for_user: |
            DELETE FROM content_pocket
            WHERE account_pocket_id = :account_pocket_id
        get_by_account_pocket_id: |
            SELECT * FROM content_pocket
            WHERE account_pocket_id = :account_pocket_id
            ORDER BY date_added DESC
            LIMIT :limit
    content_gdrive_files:
        # insert / update file modification data from user's drive
        insert_update_files_for_user: |
            INSERT INTO content_gdrive_files
            (account_gdrive_id, user_id, item_id, json, date_added, date_updated)
            VALUES
            (:account_gdrive_id, :user_id, :item_id, :json, :date_added, :date_updated)
                ON DUPLICATE KEY UPDATE json = :json, date_updated = :date_updated
        delete_content_for_user: |
            DELETE FROM content_gdrive_files
            WHERE account_gdrive_id = :account_gdrive_id
        get_by_account_gdrive_id: |
            SELECT * FROM content_gdrive_files
            WHERE account_gdrive_id = :account_gdrive_id
            ORDER BY date_updated DESC
            LIMIT :limit
    content_youtube:
        # insert / update file modification data from user's drive
        insert_update_content_for_user: |
            INSERT INTO content_youtube
            (account_gdrive_id, user_id, item_id, json, date_added, date_updated)
            VALUES
            (:account_gdrive_id, :user_id, :item_id, :json, :date_added, :date_updated)
                ON DUPLICATE KEY UPDATE json = :json, date_updated = :date_updated
        delete_content_for_user: |
            DELETE FROM content_youtube
            WHERE account_gdrive_id = :account_gdrive_id
        get_by_account_gdrive_id: |
            SELECT * FROM content_youtube
            WHERE account_gdrive_id = :account_gdrive_id
            ORDER BY date_updated DESC
            LIMIT :limit
    projects:
        insert: |
            INSERT INTO projects
            (user_id, name, description, date_added, date_updated)
            VALUES
            (:user_id, :name, :description,  NOW(), NOW())
        select_by_id: |
            SELECT * FROM projects
            WHERE id = :id AND user_id = :user_id
        select_by_user: |
            SELECT * FROM projects
            WHERE user_id = :user_id
            ORDER BY date_updated DESC
        update: |
            UPDATE projects
            SET
                name = :name,
                description = :description,
                date_updated = NOW()
            WHERE
                id = :id
            AND
                user_id = :user_id
    project_storyboards:
        select_by_project: |
            SELECT * FROM project_storyboards
            WHERE user_id = :user_id
            AND project_id = :project_id
            ORDER BY date_updated DESC
        select_by_id: |
            SELECT * FROM project_storyboards
            WHERE user_id = :user_id
            AND id = :id
            ORDER BY date_updated DESC
