security:
    secret: :SECURITY_SECRET
mysql:
    host: :MYSQL_HOST
    database: :MYSQL_DATABASE
    user: :MYSQL_USER
    password: :MYSQL_PASSWORD
service:
    pocket:
        consumer_key: :POCKET_CONSUMER_KEY
sql:
    users:
        # get by id
        get_by_id: |
            SELECT id, username, email FROM users WHERE id = :id
        # authorization query
        select_by_username_and_password: |
            SELECT id, email, username
            FROM `users`
            WHERE username = :username
            AND password = :password
    account_pocket:
        # insert-update pocket account
        insert_update_pocket_user: |
            INSERT INTO account_pocket
            (user_id, username, access_token, date_added, date_updated)
            VALUES
            (:user_id, :username, :access_token, NOW(), NOW())
                ON DUPLICATE KEY UPDATE access_token = :access_token, date_updated = NOW()
        get_pocket_users: |
            SELECT * FROM account_pocket
    content_pocket:
        insert_update_pocket_content_for_user: |
            INSERT INTO content_pocket
            (user_id, item_id, json, date_added, date_updated)
            VALUES
            (:user_id, :item_id, :json, :date_added, :date_updated)
                ON DUPLICATE KEY UPDATE json = :json, date_updated = :date_updated
