gallery001:
    category:
        -
            id: illustration
            name: "Illustration"
        -
            id: animation
            name: "Animation"
        -
            id: comic
            name: "Comic"
        -
            id: print_design
            name: "Print Design"
        -
            id: webdev
            name: "Web Development / Design"
        -
            id: character_design
            name: "Character Design"
        -
            id: instagram
            name: "Instagram"
    gallery:
        -
            title: "Sauced Octopus"
            year: "2008"
            medium: "pencil, Painter, Photoshop"
            category_id: illustration
            type: "image"
            content: "https://farm3.staticflickr.com/2473/3692721420_0cee6cd9d2_b.jpg"
            thumbnail: "https://c1.staticflickr.com/3/2473/3692721420_0cee6cd9d2.jpg"
            description: "Just an illustration I used to sell prints of."
        -
            title: "Cute Animals (animatic)"
            year: "2007"
            medium: "pencil, Photoshop, Flash"
            category_id: animation
            type: "embed"
            content: >
              <iframe width="900" height="504" src="https://www.youtube.com/embed/iRTw-bKBIeI" frameborder="0" allowfullscreen></iframe>
            thumbnail: "http://img.youtube.com/vi/iRTw-bKBIeI/mqdefault.jpg"
            description: "An animatic for the song \"Cute Animals\" by Gary Wertz. https://www.youtube.com/embed/iRTw-bKBIeI"
        -
            title: "Eyeguy Animation Test"
            year: "2007"
            medium: "pencil, Painter, Photoshop, Flash"
            category_id: animation
            type: "embed"
            content: >
              <iframe width="900" height="504" src="https://www.youtube.com/embed/MVC4mg46haM" frameborder="0" allowfullscreen></iframe>
            thumbnail: "http://img.youtube.com/vi/MVC4mg46haM/0.jpg"
            description: "A character test for Eyeguy at the office. https://www.youtube.com/watch?v=MVC4mg46haM"
        -
            title: "Tweetstream and Zeitgeist in: On the Scene"
            year: "2014"
            medium: "Painter"
            category_id: comic
            type: "image"
            content: "http://images.rishisatsangi.com/comics/life-in-the-cloud/on-the-scene-part-1/02.jpg"
            thumbnail: "https://c2.staticflickr.com/6/5814/22237250364_1932310813.jpg"
            description: >
              Twitter and Google have their own superheroes - Tweetstream and Zeitgeist, respectively.
              [Check out the comic here](/comics/tweetstream-and-zeitgeist).
        -
            title: "masthead for learning to experiment blog"
            year: "2009"
            medium: "Painter"
            category_id: illustration
            type: "image"
            content: "https://farm4.staticflickr.com/3419/3918604896_948bb5fb23_b.jpg"
            thumbnail: "https://c2.staticflickr.com/4/3419/3918604896_948bb5fb23.jpg"
            description: "A masthead for a friend's cooking blog"
        -
            title: "audio van gogh - driving music (cd insert inside)"
            year: "2004"
            medium: "Maya, Photoshop, InDesign"
            category_id: print_design
            type: "image"
            content: "https://farm4.staticflickr.com/3200/2852136437_6aa93fa9bc_o.jpg"
            thumbnail: "https://c2.staticflickr.com/4/3200/2852136437_c966b31ef3.jpg"
            description: "CD insert art for artist Audio Van Gogh"
        -
            title: "CD Album art |  Routine Life by John hRuby"
            year: "2009"
            medium: "Photography, Illustrator, Photoshop"
            category_id: print_design
            type: "image"
            content: "https://farm5.staticflickr.com/4041/4211926998_89a464b489_b.jpg"
            thumbnail: "https://c1.staticflickr.com/5/4041/4211926998_89a464b489.jpg"
            description: "CD case cover for album by John Hruby http://www.iheart.com/artist/john-hruby-288206/"
        -
            title: "My Mango Tango Book Cover"
            year: "2011"
            medium: "Painter, Photoshop, Illustrator"
            category_id: print_design
            type: "image"
            content: "https://farm8.staticflickr.com/7130/7751591522_8dcca9f7ed_b.jpg"
            thumbnail: "https://c1.staticflickr.com/7/6158/6195612026_391c54cdb4.jpg"
            description: "A book cover for author Nisha Mathur about an indian woman assimilating in the US."
        -
            title: "The Dwarves Website"
            year: "2006"
            medium: "Photoshop, Dreamweaver, Wordpress, PHP, MySQL, HTML, Flash, Javascript, CSS"
            category_id: webdev
            type: "image"
            content: "https://farm4.staticflickr.com/3060/2852102371_9f5d32ba0e_o.jpg"
            thumbnail: "https://c2.staticflickr.com/4/3060/2852102371_3d7b5a5971.jpg"
            description: "Website for the Dwarves http://thedwarves.com\n* Image uploading with automatic resizing\n* \"Gallerain\" Flash/MySQL based image rotator\n* Integrated WordPress blog\n* Presskit Hi-res media uploads"
        -
            title: "Bandbajgayi.com"
            year: "2015"
            medium: "Photoshop, PHP, HTML, Javascript, CSS"
            category_id: webdev
            type: "image"
            content: "https://farm1.staticflickr.com/689/20249444023_21650c811e_b.jpg"
            thumbnail: "https://c1.staticflickr.com/1/689/20249444023_21650c811e.jpg"
            description: "This is my own wedding website which I designed with my wife :) -- fully functional feature-rich wedding website. I can make one for you. http://bandbajgayi.com"
        -
            title: "Beepo Takes A Pipe To Nowhere"
            year: "2010"
            medium: "pencil, Painter, Photoshop"
            category_id: illustration
            type: "image"
            content: "https://farm3.staticflickr.com/2439/3663515635_1c89de110c_b.jpg"
            thumbnail: "https://c1.staticflickr.com/3/2439/3663515635_1c89de110c.jpg"
            description: "Beepo is a robot built by Japanese robotics engineers with whatever information they had about Italian stereotypes. Upon his activation they uploaded the occupation \"plumber\" into his main fucking memory.\nIn this world there are no humans around but somehow he always has a pipe to clean out or something to unclog. It's a very septic life. He tends to drink and do a lot of drugs, even on the job.\nBut he also has a stereotypically Italian lust for life, and he sings Opera to all the beautiful women ... robots. Women robots.\nThis piece is concept art for a mini film starring the one and only Beepo Beeparelli"
        -
            title: "Burger Pope Ad"
            year: "2007"
            medium: "pencil, Painter, Photoshop"
            category_id: illustration
            type: "image"
            content: "https://farm2.staticflickr.com/1156/1467947071_28963a1d91_o.jpg"
            thumbnail: "https://c2.staticflickr.com/2/1156/1467947071_8a362db26e.jpg"
            description: "Burger Pope!"
        -
            title: "Beepo Concept Art"
            year: "2009"
            medium: "Painter"
            category_id: character_design
            type: "image"
            content: "https://farm3.staticflickr.com/2533/3996839316_699ee275b7_b.jpg"
            thumbnail: "https://c1.staticflickr.com/3/2533/3996839316_699ee275b7.jpg"
            description: "Character designs for Beepo Beeparelli"
        -
            title: "Beepo Doesn't Get Turtles"
            year: "2010"
            medium: "pencil"
            category_id: character_design
            type: "image"
            content: "https://farm3.staticflickr.com/2786/4326820558_3db6e6beee_b.jpg"
            thumbnail: "https://c1.staticflickr.com/3/2786/4326820558_3db6e6beee.jpg"
            description: "Character design for Beepo Beeparelli"
        -
            title: "Uranium 239 Pops"
            year: "1997"
            medium: "Painter"
            category_id: illustration
            type: "image"
            content: "https://farm1.staticflickr.com/175/461988892_d37e43bae6_o.jpg"
            thumbnail: "https://c1.staticflickr.com/1/175/461988892_6569620052.jpg"
            description: "Uranium 239 Glow Pops"
fountain001:
    example: >
        Title:
            _**BOB SHAZBUTT**_
            _**These Bands All Suck**_
        Credit: Written by
        Author: Rishi Satsangi
        Draft date: 11/03/2015
        Contact:
            @dethbird

        EXT. The street

        We see BOB standing next to a poster for a Lady Vajayjay concert here in Boogertown. His cellphone starts beeping, so he pulls it out of his pocket while LARRY JOE CODY ALLUITIOUS walks by.

        LARRY
        (excitedly)
        Hey, BOB!

        BOB
        Oh hey Larry whats up?

        BOB wants to check his phone but LARRY is a talkative guy.

        LARRY
        Oh not much just working on some stuff. Actually it's pretty cool, we've been getting a bunch of metrics so the boys over in engineering have been monkeying around I think they've got a pretty good algorithm for pulling out some pretty key data. Anyway, I've been

        BOB is struggling to try and aim his eyes at his phone and read when the message on his phone was about.

        BOB
        Oh yea?

        LARRY
        Yea, I'm going to ....

        [[ And on and like that ]]

        BOB
        (to himself)
        Ah carps, why did I engage him.
