gallery001:
    images:
        -
            url: "https://c2.staticflickr.com/4/3273/2737012930_6969579b01_o.jpg"
        -
            url: "https://c1.staticflickr.com/3/2163/1588423948_9910bd797b_o.jpg"
        -
            url: "https://c1.staticflickr.com/5/4038/4160567168_9856235670_o.jpg"
fountain001:
    example: >
        Title:
            _**BOB SHAZBUTT**_
            _**These Bands All Suck**_
        Credit: Written by
        Author: Rishi Satsangi
        Draft date: 11/03/2015
        Contact:
            @dethbird

        EXT. The street

        We see BOB standing next to a poster for a Lady Vajayjay concert here in Boogertown. His cellphone starts beeping, so he pulls it out of his pocket while LARRY JOE CODY ALLUITIOUS walks by.

        LARRY
        (excitedly)
        Hey, BOB!

        BOB
        Oh hey Larry whats up?

        BOB wants to check his phone but LARRY is a talkative guy.

        LARRY
        Oh not much just working on some stuff. Actually it's pretty cool, we've been getting a bunch of metrics so the boys over in engineering have been monkeying around I think they've got a pretty good algorithm for pulling out some pretty key data. Anyway, I've been

        BOB is struggling to try and aim his eyes at his phone and read when the message on his phone was about.

        BOB
        Oh yea?

        LARRY
        Yea, I'm going to ....

        [[ And on and like that ]]

        BOB
        (to himself)
        Ah carps, why did I engage him.
