-
  login: dethbird
  email: rishi.satsangi@gmail.com
  password: uranium239
  projects:
    - beepo
    - marqueeshade
    - nxmw
    - robotstandup
-
  login: jon.earp
  email: jon.earp@gmail.com
  password: P1zzaP4rty!!!
  projects:
    - nxmw
-
  login: prutha.raithatha
  email: prutharaithatha@gmail.com
  password: apple
  projects:
    - beepo
    - marqueeshade
    - nxmw
-
  login: keyur.joshi
  email: joshi.kb85@gmail.com
  password: P1zzaP4rty!!!
  projects:
    - beepo
    - marqueeshade
-
  login: schloss
  email: dave@themeat.org
  password: P1zzaP4rty!!!
  projects:
    - marqueeshade
    - beepo
-
  login: nick.roberts
  email: dreadwestern@gmail.com
  password: P1zzaP4rty!!!
  projects:
    - marqueeshade
    - robotstandup
