-
  login: dethbird
  email: rishi.satsangi@gmail.com
  password: uranium239
  projects:
    - beepo
    - marqueeshade
    - nxmw
-
  login: jon.earp
  email: jon.earp@gmail.com
  password: P1zzaP4rty!!!
  projects:
    - nxmw
