name: Animation
list:
  -
    name: Interview with John Lassiter
    description: |
      https://www.youtube.com/watch?v=00hDSOCQy4s
      https://www.youtube.com/watch?v=VmUzwM89Fdw
    tags:
      - interview
    date_added: 2015-12-14
  -
    name: Interview with John Lassiter
    description: |
      https://www.youtube.com/watch?v=00hDSOCQy4s
      https://www.youtube.com/watch?v=VmUzwM89Fdw
    tags:
      - interview
    date_added: 2015-12-14
  -
    name: Interview with John Lassiter
    description: |
      https://www.youtube.com/watch?v=00hDSOCQy4s
      https://www.youtube.com/watch?v=VmUzwM89Fdw
    tags:
      - interview
    date_added: 2015-12-14
  -
    name: Interview with John Lassiter
    description: |
      https://www.youtube.com/watch?v=00hDSOCQy4s
      https://www.youtube.com/watch?v=VmUzwM89Fdw
    tags:
      - interview
    date_added: 2015-12-14
  -
    name: Interview with John Lassiter
    description: |
      https://www.youtube.com/watch?v=00hDSOCQy4s
      https://www.youtube.com/watch?v=VmUzwM89Fdw
    tags:
      - interview
    date_added: 2015-12-14
  -
    name: Interview with John Lassiter
    description: |
      https://www.youtube.com/watch?v=00hDSOCQy4s
      https://www.youtube.com/watch?v=VmUzwM89Fdw
    tags:
      - interview
    date_added: 2015-12-14                    
