name: The World of Beepo Beeparelli
description: |
  Beepo is a robot built by Japanese robotics engineers with whatever information they had about Italian stereotypes. Upon his activation they uploaded the occupation "plumber" into his main fucking memory.

  In this world there are no humans around but somehow he always has a pipe to clean out or something to unclog. It's a very septic life. He tends to drink and do a lot of drugs, even on the job.

  But he also has a stereotypically Italian lust for life, and he sings Opera to all the beautiful women ... robots. Women robots.
characters:
  render: true
  description: |
    The characters
  list:
    -
      id: beepo_beeparelli
      name: Beepo Beeparelli
      occupation: Plumber
      role: lead
      images:
        -
          orientation: portrait
          thumbnail: https://c1.staticflickr.com/3/2533/3996839316_699ee275b7.jpg
          display: https://c1.staticflickr.com/3/2533/3996839316_699ee275b7_b.jpg
      description: |
        He was programmed by 1980's Japanese scientists to be an Italian plumber for some fucking reason.
    -
      id: coal_train
      name: Coal Train
      occupation: Bartender
      role: supporting
      images:
        -
          orientation: portrait
          thumbnail: https://c2.staticflickr.com/6/5707/23456678931_7624c0cc81.jpg
          display: https://c2.staticflickr.com/6/5707/23456678931_2a1f606357_o.jpg
          images:
        -
          orientation: landscape
          thumbnail: https://c2.staticflickr.com/6/5769/22912334113_569879bae9.jpg
          display: https://c2.staticflickr.com/6/5769/22912334113_569879bae9_b.jpg
      description: |
        A decomissioned military robot repurposed as a bartender. His database makes him the perfect advice giver because he can run a query on existing conversations with clientele.
    -
      name: ???
      occupation: ???
      role: supporting
      status: idea
      description: |
        A bar buddy
    -
      name: ???
      occupation: Princess
      role: lead
      status: idea
      description: |
        The princess at the abandoned amusement park.
    -
      name: ???
      occupation: Drug Dealer
      role: other
      status: idea
      description: |
        the futuristic robot guy that sells beepo drugs
themes:
  render: true
  list:
    -
      name: Identity
      description: |
        Do you have to be what you were programmed to be?
    -
      name: Drugs
      description: |
        Societal attitudes toward substance use and abuse. People that traffic stereotypes.
inspirations:
  render: true
  description: |
    Visual and stylistic inspirational sources
  list:
    -
      name: Mario
      type: video game
      description: |
        Especially Super Mario 2 with the theatrics and curtains and all.
plots:
  render: true
  list:
    -
      name: ???
      type: Episode
      status: idea
      description: |
        Beepo gets hammered and breaks bricks and collects coins and sings opera one night.
locations:
  render: true
  description: |
    A weird mix between Vegas, NYC, and LA.
  list:
    -
      name: Stankin' Hole
      type: bar
      description: |
        Local worker class pub
    -
      name: Abandoned Amusement Park
      type: amusement park
      description: |
        The abandoned amusement park where the princess lives
    -
      name: City Apartments
      type: apartments
      status: idea
      description: |
        Random people's apartments around the city
concept_art:
  render: true
  list:
    -
      id: 10001
      name: Beepo Takes a Pipe to Nowhere
      description: |
        Beepo takes a pipe to nowhere
      images:
        -
          orientation: landscape
          thumbnail: https://c1.staticflickr.com/3/2439/3663515635_1c89de110c.jpg
          display: https://c1.staticflickr.com/3/2439/3663515635_1c89de110c_b.jpg
    -
      id: 10002
      name: Night Brickin'
      status: idea
      description: |
        Beepo hammered destroying bricks at night
    -
      id: 10003
      name: Apartments of the City
      status: idea
      description: |
        Random apartment interiors in the city
